# Generated by Django 4.1 on 2023-01-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='datainfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default='', max_length=30, unique=True, verbose_name='日期')),
                ('imagesrc', models.CharField(default='', max_length=30, verbose_name='影像类型')),
                ('imagename', models.CharField(default='', max_length=50, verbose_name='影像名称')),
            ],
            options={
                'db_table': 'image_data',
            },
        ),
    ]
